site_name: SimpleMatchmaking Documentation
site_url: https://ekody.github.io/SimpleMatchmaking/
nav:
  - Introduction: 'index.md'
  - Objects:
    - MatchmakingQueue: 'MatchmakingQueue.md'
    - QueueOptions: 'QueueOptions.md'
  - About:
    - 'Updates Roadmap': 'Roadmap.md'
    - License: 'ProjectLicense.md'
theme:
  name: material
  features:
    - navigation.top
    - navigation.expand
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

markdown_extensions:
  - toc:
      title: On this page
  - md_in_html
  - tables
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - footnotes

extra:
  social:
    - icon: octicons/bug-16 
      link: https://github.com/EkoDy/SimpleMatchmaking/issues
      name: Report bugs
    - icon: octicons/checklist-16
      link: https://devforum.roblox.com/t/2850365
      name: DevForum post